AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create a random NPC
Resources:
  npc_generator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: npc.lambda_handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        NPC_Generator:
          Type: Api
          Properties:
            Path: /NPC
            Method: GET